[package]
name = "tiny-towns-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
itertools = "0.8.0"
log = "0.4.20"
strum = "0.25.0"
strum_macros = "0.25.3"
